# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1412908621);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1412908741);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1413512611);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1412908501);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1412908381);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 235520);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140924083922");
user_pref("browser.slowStartup.averageTime", 2617);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20140924083922");
user_pref("browser.startup.homepage_override.mstone", "32.0.3");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1412827631830");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1413512554619");
user_pref("datareporting.policy.firstRunTime", "1412741231830");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.firstPaint", 2578);
user_pref("datareporting.sessions.current.main", 192);
user_pref("datareporting.sessions.current.sessionRestored", 2228);
user_pref("datareporting.sessions.current.startTime", "1413512490103");
user_pref("datareporting.sessions.current.totalTime", 156);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.1", "{\"s\":1412908260229,\"a\":10,\"t\":451,\"c\":false,\"m\":183,\"fp\":2446,\"sr\":2690}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1412912723520,\"a\":6,\"t\":27,\"c\":false,\"m\":175,\"fp\":2923,\"sr\":2539}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"32.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"32.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,ubufox%40ubuntu.com:2.9,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1412908622);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1411704268000,\"rdfTime\":1390969638000}}},{\"name\":\"app-system-share\",\"addons\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1411704268000,\"rdfTime\":1379719396000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1411704268000,\"rdfTime\":1397665356000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1411704268000,\"rdfTime\":1401829706000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411704185000,\"rdfTime\":1411548820000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1411549636000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1411549636000}}}]");
user_pref("extensions.lastAppVersion", "32.0.3");
user_pref("extensions.lastPlatformVersion", "32.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140924083922");
user_pref("gecko.mstone", "32.0.3");
user_pref("idle.lastDailyNotification", 1413512719);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 14555);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1413512490);
user_pref("toolkit.telemetry.previousBuildID", "20140924083922");
